"""empty message

Revision ID: 66144a3c7093
Revises: 7ad0f8095e58
Create Date: 2026-06-22 22:23:25.335808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66144a3c7093'
down_revision = '7ad0f8095e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
